"""Measures every colour pair of the "Quiet ledger" theme against WCAG 2.1 and writes docs/redesign/tokens.md.

Text needs 4.5:1, UI edges and meaningful graphics 3:1. The values mirror ui/theme/Theme.kt; keep them in step.
Run: python scripts/contrast.py
"""
import os

THEMES = {
    "Light": dict(
        page="#FDFCFB", card="#FFFFFF", raised="#FFFFFF", sunken="#F3F2EE", hairline="#E6E4DF", outline="#85888F",
        accent="#1F3BD6", on_accent="#FFFFFF", accent_soft="#EBEEFC", ink="#111214", muted="#62666E",
        income="#007F22", expense="#B50000", neutral="#6A6F77", error_container="#FDECEC",
    ),
    "Dark": dict(
        page="#0B0B0C", card="#151618", raised="#1D1E21", sunken="#101113", hairline="#2A2B2F", outline="#6E727A",
        accent="#9DA8FF", on_accent="#0A1170", accent_soft="#1E2340", ink="#F2F2F3", muted="#A3A7AE",
        income="#4CD07D", expense="#FF7B72", neutral="#9AA0A8", error_container="#3A1210",
    ),
}

CATEGORIES = [("Food", "#D9694C"), ("Shopping", "#4F6FA0"), ("Bills", "#C08414"), ("Transport", "#5E86AA"),
              ("Entertainment", "#9B5DE5"), ("Health", "#23907F"), ("Education", "#6A7FA0"), ("Investment", "#3A9C7C"),
              ("ATM", "#7F8AA0"), ("Transfer", "#6E7FD8"), ("Income", "#2F9353"), ("Other", "#8A95A3")]


def rgb(h):
    h = h.lstrip("#")
    return [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]


def hexof(c):
    return "#" + "".join(f"{round(max(0, min(1, v)) * 255):02X}" for v in c)


def lum(h):
    f = lambda c: c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = rgb(h)
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def ratio(a, b):
    x, y = sorted([lum(a), lum(b)], reverse=True)
    return (x + 0.05) / (y + 0.05)


def over(fg, alpha, bg):
    f, b = rgb(fg), rgb(bg)
    return hexof([alpha * f[i] + (1 - alpha) * b[i] for i in range(3)])


def lerp(a, b, t):
    x, y = rgb(a), rgb(b)
    return hexof([x[i] + (y[i] - x[i]) * t for i in range(3)])


def main():
    rows = []
    for name, t in THEMES.items():
        text = [
            ("Body text", "ink", ["page", "card", "raised", "sunken"]),
            ("Secondary text", "muted", ["page", "card", "raised", "sunken"]),
            ("Accent (links, actions)", "accent", ["page", "card", "raised", "sunken", "accent_soft"]),
            ("Text on accent button", "on_accent", ["accent"]),
            ("Income", "income", ["page", "card", "raised", "sunken"]),
            ("Expense / warnings", "expense", ["page", "card", "raised", "sunken", "error_container"]),
            ("Moved (neutral)", "neutral", ["page", "card", "raised", "sunken"]),
        ]
        for label, fg, bgs in text:
            for bg in bgs:
                rows.append((name, label, t[fg], bg, t[bg], ratio(t[fg], t[bg]), 4.5))
        for label, fg, bgs in [("Control outline", "outline", ["page", "card", "raised"]), ("Accent control / selected edge", "accent", ["card", "sunken"])]:
            for bg in bgs:
                rows.append((name, label, t[fg], bg, t[bg], ratio(t[fg], t[bg]), 3.0))
        for cat, tint in CATEGORIES:
            ink = lerp(tint, "#FFFFFF", 0.45) if name == "Dark" else lerp(tint, "#000000", 0.42)
            wash = over(tint, 0.16, t["card"])
            rows.append((name, f"{cat} icon / initial on its wash", ink, "wash", wash, ratio(ink, wash), 4.5))
            rows.append((name, f"{cat} chart slice", tint, "card", t["card"], ratio(tint, t["card"]), 3.0))
        rows.append((name, "Past bars in charts", t["outline"], "card", t["card"], ratio(t["outline"], t["card"]), 3.0))

    fails = [r for r in rows if r[5] < r[6]]
    out = ["# Quiet ledger: colour tokens and contrast", "",
           "Generated by `scripts/contrast.py` from the values in `ui/theme/Theme.kt`. Text needs **4.5:1**; control",
           "edges, icons and chart marks need **3:1** (WCAG 2.1 SC 1.4.3 and 1.4.11). Hairlines are decorative and exempt.", "",
           "## Tokens", "", "| Token | Light | Dark | Use |", "|---|---|---|---|"]
    uses = dict(page="Window background", card="Cards, lists", raised="Sheets, Add button, nav pill, urgent cards (+ shadow)",
                sunken="Inputs, segment track, number pad, skeletons", hairline="Row and card separators (decorative)",
                outline="Unselected chip and control edges", accent="The one tappable colour", on_accent="Text and icons on accent",
                accent_soft="Selected chips, tinted icon squares", ink="Body text and spend amounts", muted="Secondary text",
                income="Money in", expense="Warnings, over budget, delete", neutral="Money that only moved", error_container="Error wash")
    for k in THEMES["Light"]:
        out.append(f"| `{k}` | `{THEMES['Light'][k]}` | `{THEMES['Dark'][k]}` | {uses.get(k, '')} |")
    out += ["", "Money uses **Inter Tight** (bundled, OFL) with tabular figures; everything else is **Inter**.", "",
            "## Measured pairs", "", f"{len(rows)} pairs, **{len(fails)} below their minimum**.", "",
            "| Theme | Pair | Foreground | On | Ratio | Needs | |", "|---|---|---|---|---|---|---|"]
    for th, label, fg, bgname, bg, r, need in rows:
        out.append(f"| {th} | {label} | `{fg}` | {bgname} `{bg}` | {r:.2f} | {need:g} | {'✅' if r >= need else '❌'} |")
    path = os.path.join(os.path.dirname(__file__), "..", "docs", "redesign", "tokens.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(rows)} pairs, {len(fails)} failing")
    for r in fails:
        print("FAIL", r)


if __name__ == "__main__":
    main()
